/* =====================================================================
   apply-chrome.mjs — stamp the canonical header + footer onto every page
   =====================================================================
   This repo has no build step: every page is hand-written HTML. That is
   fine until you need the SAME header on 24 of them, at which point
   hand-editing guarantees drift — which is exactly how the site ended up
   with four different headers and three different footers.

   This script is the substitute for a layout template. It:

     1. replaces whatever chrome a page currently has (`.p-nav`,
        `.blog-nav`, `.b-nav`, `nav.site-nav`, `header.site`, and the
        matching footers) with the canonical markup below;
     2. makes sure `soft.css`, `chrome.css` and `chrome.js` are linked LAST
        in <head>, each carrying a content hash in its query string.

   Re-running it is safe and idempotent: it rewrites the region between
   the chrome markers rather than appending.

       node scripts/apply-chrome.mjs           # write
       node scripts/apply-chrome.mjs --check   # report, change nothing

   Edit the HEADER / FOOTER constants here, re-run, commit the result.

   RE-RUN THIS AFTER EVERY EDIT TO soft.css / chrome.css / chrome.js — see
   the cache-busting note on hashOf() below. It is why those edits do not
   reach anyone who has already visited the site until you do.
   ===================================================================== */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SMELLOFF_PRODUCT_TRUTH as T } from '../shared/product-truth.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

const WA = String(T.whatsappNumber || '').replace(/^\+/, '');
const PRICE = T.pricePrepaid;

const COMMERCE = {
  productName: T.productName,
  brand: T.brand,
  size: T.size,
  category: T.category,
  pricePrepaid: T.pricePrepaid,
  priceCod: T.priceCod,
  codFee: T.codFee,
  mrp: T.mrp,
  spraysApprox: T.spraysApprox,
  whatsappNumber: T.whatsappNumber,
  whatsappDisplay: T.whatsappDisplay,
  madeIn: T.madeIn,
};

function hashOf(relPath) {
  try {
    return createHash('sha256')
      .update(readFileSync(join(ROOT, relPath)))
      .digest('hex')
      .slice(0, 8);
  } catch {
    return '0';
  }
}

const CART_ICON = `<svg viewBox="0 0 576 512" fill="currentColor" aria-hidden="true"><path d="M0 24C0 10.7 10.7 0 24 0L69.5 0c22 0 41.5 12.8 50.6 32l411 0c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3l-288.5 0 5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5L488 368c13.3 0 24 10.7 24 24s-10.7 24-24 24l-288.3 0c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5L24 48C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg>`;

const CART = {
  link: `<button class="sf-cart" type="button" id="cartBtn" onclick="openCartDrawer()" aria-label="Open cart">
          ${CART_ICON}
          <span class="sf-cart__count" id="sfCartCount" hidden>0</span>
        </button>`,
  drawer: `<button class="sf-cart" type="button" id="cartBtn" onclick="openCartDrawer()" aria-label="Open cart">
          ${CART_ICON}
          <span class="sf-cart__count" id="sfCartCount" hidden>0</span>
        </button>`,
};

const SKIP = `<a class="sf-skip" href="#sf-main">Skip to content</a>`;

const NAV_ITEMS = [
  ['/#buy', T.productName],
  ['/#how-it-works', 'How it works'],
  ['/reviews', 'Proof'],
  ['/blog', 'Guides'],
  ['/track-order', 'Track'],
];

const MENU_ITEMS = [
  ...NAV_ITEMS,
  ['/faq', 'FAQ'],
  ['/contact', 'Contact'],
];

const navLis = (items) =>
  items.map(([href, label]) => `          <li><a href="${href}">${label}</a></li>`).join('\n');

const header = (cart = 'drawer') => `<!-- SF-CHROME:HEADER — generated by scripts/apply-chrome.mjs. Edit there, not here. -->
${SKIP}
<script>window.SMELLOFF_TRUTH=${JSON.stringify(COMMERCE)};</script>
<header class="sf-hdr">
  <div class="sf-wrap">
    <div class="sf-hdr__row">
      <a href="/" class="sf-hdr__logo" aria-label="${T.brand} home">
        <img src="/assets/brand/logo-smelloff-white.png?v=2" alt="${T.brand.toUpperCase()}" width="1200" height="261" decoding="async">
      </a>
      <div class="sf-hdr__right">
        ${CART[cart]}
        <nav class="sf-nav-wrap" aria-label="Primary">
          <ul class="sf-nav">
${navLis(NAV_ITEMS)}
          </ul>
        </nav>
        <a href="/#buy" class="sf-hdr__cta so-btn so-btn--p1" data-smelloff-buy="header">Buy ₹${PRICE}</a>
        <button class="sf-burger" type="button" aria-expanded="false" aria-controls="sfMenu" aria-label="Open menu">
          <span></span><span></span><span></span>
        </button>
      </div>
    </div>
    <nav class="sf-hdr__menu" id="sfMenu" aria-label="Menu">
      <ul>
${navLis(MENU_ITEMS)}
      </ul>
    </nav>
  </div>
</header>
<!-- /SF-CHROME:HEADER -->`;

const HEADER = header();

const SOCIALS = [
  ['https://instagram.com/smelloffindia', 'Instagram', 'icon-instagram-white.png'],
  ['https://x.com/smelloffindia', 'X (Twitter)', 'icon-x.png'],
  ['https://t.me/smelloffindia', 'Telegram', 'icon-telegram-white.png'],
  ['https://www.linkedin.com/company/smelloff', 'LinkedIn', 'icon-linkedin-white.png'],
  ['https://www.facebook.com/share/1BU1dCAttY/', 'Facebook', 'icon-facebook-white.png'],
  [`https://wa.me/${WA}`, 'WhatsApp', 'icon-whatsapp-white.png'],
]
  .map(
    ([href, label, icon]) =>
      `        <a href="${href}" target="_blank" rel="noopener" aria-label="${label}"><img src="/assets/${icon}" alt="" width="20" height="20" loading="lazy"></a>`
  )
  .join('\n');

const FOOTER = `<!-- SF-CHROME:FOOTER — generated by scripts/apply-chrome.mjs. Edit there, not here. -->
<footer class="sf-ftr">
  <div class="sf-wrap">
    <div class="sf-ftr__grid">
      <div class="sf-ftr__brand">
        <img src="/assets/brand/logo-smelloff-white.png?v=2" alt="${T.brand.toUpperCase()}" width="1200" height="261" loading="lazy">
        <p>${T.category}. Made in ${T.madeIn}.</p>
      </div>
      <div>
        <h3>Shop</h3>
        <ul>
          <li><a href="/#buy">${T.productName}</a></li>
          <li><a href="/blog/how-to-use-odorstrike">How to use</a></li>
          <li><a href="/reviews">Reviews</a></li>
          <li><a href="/blog">Guides</a></li>
          <li><a href="/track-order">Track order</a></li>
        </ul>
      </div>
      <div>
        <h3>Support</h3>
        <ul>
          <li><a href="/shipping">Shipping</a></li>
          <li><a href="/returns">Returns</a></li>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>
      <div>
        <h3>Company</h3>
        <ul>
          <li><a href="/about">About</a></li>
          <li><a href="https://partners.smelloff.in">Partners</a></li>
          <li><a href="/llms.txt">llms.txt</a></li>
          <li><a href="/feed.xml">RSS</a></li>
        </ul>
      </div>
      <div>
        <h3>Legal</h3>
        <ul>
          <li><a href="/privacy">Privacy</a></li>
          <li><a href="/terms">Terms</a></li>
          <li><a href="/refund">Refunds</a></li>
          <li><a href="/cancellation">Cancellation</a></li>
        </ul>
      </div>
      <div class="sf-ftr__socials">
${SOCIALS}
      </div>
    </div>
    <div class="sf-ftr__bottom">
      <span>© 2026 ${T.brand}. ${T.manufacturer.address}</span>
      <span>Made in India · Fabric only</span>
    </div>
    <div class="sf-ftr__disclaimer">
      <span>Febreze, Ambi Pur and all other product names, logos and brands mentioned on this site are the property of their respective owners. Smelloff is not affiliated with, endorsed by or sponsored by any of them. Comparisons are our own independent assessments, published for information only.</span>
    </div>
  </div>
</footer>
<!-- /SF-CHROME:FOOTER -->`;

const BUY_MODULE = `<!-- SF-CHROME:BUY — generated by scripts/apply-chrome.mjs. Edit there, not here. -->
<aside class="so-buy" data-so-buy aria-label="Buy ${T.productName}">
  <div class="sf-wrap">
    <div class="so-buy__panel">
      <p class="so-buy__kicker">${T.brand}</p>
      <h2 class="so-buy__name" data-so-name>${T.productName}</h2>
      <p class="so-buy__cat" data-so-cat>${T.size} ${T.category}</p>
      <div class="so-pay" role="group" aria-label="Payment method">
        <button type="button" class="so-pay__opt" data-so-pay="prepaid" aria-pressed="true">
          <span class="so-pay__label">Prepaid UPI</span>
          <span class="so-pay__price" data-so-prepaid-price>₹${T.pricePrepaid}</span>
          <span class="so-pay__note">Free shipping</span>
        </button>
        <button type="button" class="so-pay__opt" data-so-pay="cod" aria-pressed="false">
          <span class="so-pay__label">COD</span>
          <span class="so-pay__price" data-so-cod-price>₹${T.priceCod}</span>
          <span class="so-pay__note" data-so-cod-fee>₹${T.codFee} handling</span>
        </button>
      </div>
      <a class="so-btn so-btn--p1 so-buy__cta" href="/?buy=1" data-so-cta data-smelloff-buy="buymodule">Buy ${T.productName} — ₹${T.pricePrepaid}</a>
      <div class="so-buy__wa">
        <a class="so-btn so-btn--p3" data-so-wa href="https://wa.me/${WA}?text=${encodeURIComponent('Hi Smelloff, I would like to order ODORSTRIKE 50ml.')}">Order on WhatsApp</a>
      </div>
      <ul class="so-buy__trust">
        <li>Free shipping on prepaid UPI</li>
        <li>COD ₹${T.priceCod} at the door</li>
        <li>Dispatched ${T.dispatchWindow.toLowerCase()}</li>
        <li>${T.madeIn}</li>
      </ul>
    </div>
  </div>
</aside>
<!-- /SF-CHROME:BUY -->`;

const PAGES = [
  ...[
    'faq.html', 'about.html', 'contact.html', 'reviews.html', 'track-order.html',
    'privacy.html', 'terms.html', 'returns.html', 'refund.html', 'shipping.html',
    'cancellation.html', 'payment-failed.html',
  ].map((f) => ({
    file: f,
    header: ['privacy.html', 'terms.html'].includes(f) ? 'header.top-bar' : 'nav.p-nav',
    footer: 'footer',
    buy: ['faq.html', 'about.html', 'contact.html', 'reviews.html'].includes(f),
  })),
  { file: '404.html', header: 'nav.blog-nav', footer: 'footer.blog-footer' },
  { file: 'blog/index.html', header: 'nav.b-nav', footer: 'footer.blog-footer' },
  ...[
    'why-i-built-odorstrike', 'odorstrike-review-30-day-india-test',
    'odorstrike-vs-febreze-india', 'ambi-pur-vs-odorstrike',
    'what-is-fabric-odor-eliminator', 'hpbcd-cyclodextrin-fabric-odor',
    'zinc-pca-fabric-odor-ingredient-guide', 'beta-cyclodextrin-odor-removal-science',
    'best-fabric-odor-spray-india-2026-body-odor', 'best-deodorant-spray-for-clothes-not-skin',
    'deodorant-vs-fabric-mist', 'spray-to-remove-sweat-smell-from-clothes-quickly',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  ...[
    'does-fabric-spray-stain-clothes', 'gym-clothes-smell-after-washing',
    'odorstrike-ingredients', 'wedding-festive-wear-odor-guide', 'how-to-use-odorstrike',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  ...[
    'damp-clothes-musty-smell-monsoon-fix', 'how-often-to-wash-jeans-india',
    'keep-clothes-fresh-while-travelling', 'which-fabrics-hold-odor-most',
    'fabric-deodorizer-spray-india-guide-2026',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  ...[
    'remove-cooking-smell-from-clothes', 'remove-smell-from-hoodie-without-washing',
    'keep-clothes-fresh-without-washing-machine', 'remove-cigarette-smoke-smell-from-clothes',
    'remove-mothball-almirah-smell-from-clothes', 'keep-office-trousers-fresh-without-washing',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  ...[
    'how-to-freshen-clothes-stored-for-months',
    'how-to-pack-sweaty-clothes-without-bag-smell',
    'odor-on-clothes-vs-odor-in-clothes',
    'why-body-odor-comes-back-on-clothes-so-quickly',
    'why-clean-shirt-starts-smelling-within-hours',
    'why-clothes-smell-bad-after-drying',
    'why-clothes-smell-bad-again-after-sweating',
    'why-clothes-smell-in-wardrobe-even-when-clean',
    'why-polyester-holds-odor-longer-than-cotton',
    'why-clothes-smell-musty-after-being-stored',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  ...[
    'solutions/index.html',
    'solutions/monsoon-damp-fabric-care.html',
    'solutions/post-gym-workout-sweat-spray.html',
    'solutions/office-commute-fabric-refresher.html',
    'solutions/denim-outerwear-dry-care.html',
  ].map((f) => ({ file: f, header: 'header', footer: 'footer', buy: true })),
  { file: 'index.html', header: 'header.site', footer: 'footer' },
];

function stripBrokenChromePrefix(html) {
  const headerAt = html.indexOf('<header class="sf-hdr"');
  if (headerAt === -1) return html;
  const before = html.slice(0, headerAt);
  const markers = (before.match(/<!-- SF-CHROME:HEADER/g) || []).length;
  const skips = (before.match(/<a class="sf-skip"/g) || []).length;
  if (markers <= 1 && skips <= 1) return html;
  const cleaned = before
    .replace(/<!-- SF-CHROME:HEADER[\s\S]*?-->/g, '')
    .replace(/<a class="sf-skip"[^>]*>Skip to content<\/a>/g, '')
    .replace(/<script>window\.SMELLOFF_TRUTH=.*?<\/script>/g, '');
  return cleaned + html.slice(headerAt);
}

function findBlock(html, selector) {
  const [tag, cls] = selector.split('.');
  const openRe = new RegExp(`<${tag}(\\s[^>]*)?>`, 'gi');
  let m;
  while ((m = openRe.exec(html))) {
    const attrs = m[1] || '';
    if (cls) {
      const c = /class\s*=\s*"([^"]*)"/i.exec(attrs);
      if (!c || !c[1].split(/\s+/).includes(cls)) continue;
    }
    const walk = new RegExp(`<(/?)${tag}(\\s[^>]*)?>`, 'gi');
    walk.lastIndex = m.index;
    let depth = 0, w;
    while ((w = walk.exec(html))) {
      depth += w[1] === '/' ? -1 : 1;
      if (depth === 0) return { start: m.index, end: w.index + w[0].length };
    }
  }
  return null;
}

function withMarkers(html, block, kind) {
  let { start, end } = block;
  const open = `<!-- SF-CHROME:${kind}`;
  const close = `<!-- /SF-CHROME:${kind} -->`;
  const before = html.lastIndexOf(open, start);
  if (before !== -1 && start - before < 800) start = before;
  const after = html.indexOf(close, end);
  if (after !== -1 && after - end < 400) end = after + close.length;
  if (kind === 'HEADER') {
    const skipAt = Math.max(
      html.lastIndexOf('<a class="skip"', start),
      html.lastIndexOf('<a class="sf-skip"', start),
      html.lastIndexOf('<a href="#content" class="skip-link"', start),
    );
    if (skipAt !== -1 && start - skipAt < 160) start = skipAt;
  }
  return { start, end };
}

function cutBuy(html, footerStart) {
  const open = html.lastIndexOf('<!-- SF-CHROME:BUY', footerStart);
  if (open !== -1 && footerStart - open < 8000) return open;
  return footerStart;
}

function ensureHreflangHead(headHtml) {
  const can = (headHtml.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)/i) || [])[1];
  if (!can || /noindex/i.test(headHtml)) return headHtml;
  const tags = `  <link rel="alternate" hreflang="en-IN" href="${can}">\n  <link rel="alternate" hreflang="x-default" href="${can}">`;
  let out = headHtml.replace(/\s*<link rel="alternate" hreflang="[^"]+" href="[^"]*"\s*\/?>/gi, '');
  if (/rel=["']canonical["']/i.test(out)) {
    out = out.replace(/(<link[^>]+rel=["']canonical["'][^>]*>)/i, `$1\n${tags}`);
  }
  return out;
}

function ensureAssets(html) {
  const softTag = `<link rel="stylesheet" href="/assets/css/soft.css?v=${hashOf('assets/css/soft.css')}">`;
  const chromeTag = `<link rel="stylesheet" href="/assets/css/chrome.css?v=${hashOf('assets/css/chrome.css')}">`;
  const checkoutCssTag = `<link rel="stylesheet" href="/assets/css/checkout.css?v=${hashOf('assets/css/checkout.css')}">`;
  const jsTag = `<script src="/assets/js/chrome.js?v=${hashOf('assets/js/chrome.js')}" defer></script>`;
  const checkoutJsTag = `<script src="/assets/js/checkout.js?v=${hashOf('assets/js/checkout.js')}" defer></script>`;
  const buyTag = `<script type="module" src="/assets/js/buy-module.js?v=${hashOf('assets/js/buy-module.js')}"></script>`;
  const tokensTag = `<link rel="stylesheet" href="/assets/css/tokens.css?v=${hashOf('assets/css/tokens.css')}">`;
  const fontsTag = `<link rel="stylesheet" href="/assets/fonts.css?v=${hashOf('assets/fonts.css')}">`;
  const llmsTag = `<link rel="alternate" type="text/plain" title="LLM content" href="https://smelloff.in/llms.txt">`;
  const rssTag = `<link rel="alternate" type="application/rss+xml" title="Smelloff guides" href="https://smelloff.in/feed.xml">`;

  html = html.replace(/[ \t]*<!-- Shared layers load LAST[^>]*-->\n?/g, '');
  html = html.replace(
    /[ \t]*<link[^>]+href="\/assets\/css\/(?:soft|chrome|checkout)\.css[^"]*"[^>]*>\n?/g,
    ''
  );
  html = html.replace(
    /[ \t]*<script[^>]+src="\/assets\/js\/chrome\.js[^"]*"[^>]*><\/script>\n?/g,
    ''
  );
  html = html.replace(
    /[ \t]*<script[^>]+src="\/assets\/js\/checkout\.js[^"]*"[^>]*><\/script>\n?/g,
    ''
  );
  html = html.replace(
    /[ \t]*<script[^>]+src="\/assets\/js\/buy-module\.js[^"]*"[^>]*><\/script>\n?/g,
    ''
  );
  html = html.replace(/[ \t]*<link[^>]+fonts\.googleapis\.com[^>]*>\n?/g, '');
  html = html.replace(/[ \t]*<link[^>]+fonts\.gstatic\.com[^>]*>\n?/g, '');
  html = html.replace(/[ \t]*<link rel="preconnect"[^>]+fonts\.(googleapis|gstatic)\.com[^>]*>\n?/g, '');

  for (const [file, pattern] of [
    ['assets/css/tokens.css', /(href="\/assets\/css\/tokens\.css)(\?[^"]*)?"/g],
    ['assets/fonts.css', /(href="\/assets\/fonts\.css)(\?[^"]*)?"/g],
    ['assets/css/blog.css', /(href="\/assets\/css\/blog\.css)(\?[^"]*)?"/g],
    ['assets/js/consent-analytics.js', /(src="\/assets\/js\/consent-analytics\.js)(\?[^"]*)?"/g],
    ['assets/js/track.js', /(src="\/assets\/js\/track\.js)(\?[^"]*)?"/g],
    ['assets/js/google-customer-reviews.js', /(src="\/assets\/js\/google-customer-reviews\.js)(\?[^"]*)?"/g],
  ]) {
    const v = hashOf(file);
    if (v) html = html.replace(pattern, `$1?v=${v}"`);
  }

  const headEnd = html.lastIndexOf('</head>');
  if (headEnd === -1) return html;
  const hasTokens = /href="\/assets\/css\/tokens\.css/.test(html.slice(0, headEnd));
  const hasFonts = /href="\/assets\/fonts\.css/.test(html.slice(0, headEnd));
  const hasLlms = /href="https:\/\/smelloff\.in\/llms\.txt"/.test(html.slice(0, headEnd));
  const hasRss = /type="application\/rss\+xml"/.test(html.slice(0, headEnd));
  let next = html.slice(0, headEnd);
  if (!hasTokens) next += tokensTag + '\n';
  if (!hasFonts) next += fontsTag + '\n';
  if (!hasLlms) next += llmsTag + '\n';
  if (!hasRss) next += rssTag + '\n';
  next = ensureHreflangHead(next);
  return (
    next +
    `<!-- Shared layers load LAST so they win on source order; ?v= is a content hash (cache busting). See scripts/apply-chrome.mjs. -->\n` +
    `${softTag}\n${checkoutCssTag}\n${chromeTag}\n${jsTag}\n${checkoutJsTag}\n${buyTag}\n` +
    html.slice(headEnd)
  );
}

const CHECKOUT_HTML = readFileSync(join(ROOT, '_shared/checkout.html'), 'utf8');

function ensureCheckout(html) {
  html = html.replace(/\s*<!-- SF-CHROME:CHECKOUT[\s\S]*?<!-- \/SF-CHROME:CHECKOUT -->\n?/g, '\n');
  const bodyEnd = html.lastIndexOf('</body>');
  if (bodyEnd === -1) return html;
  return html.slice(0, bodyEnd) + CHECKOUT_HTML + '\n' + html.slice(bodyEnd);
}

function ensureShareScript(html) {
  html = html.replace(
    /[ \t]*<script[^>]+src="\/assets\/js\/blog-share\.js[^"]*"[^>]*><\/script>\n?/g,
    ''
  );
  if (!/class="post-share"/.test(html)) return html;

  const bodyEnd = html.lastIndexOf('</body>');
  if (bodyEnd === -1) return html;
  const v = hashOf('assets/js/blog-share.js');
  return (
    html.slice(0, bodyEnd) +
    `<script src="/assets/js/blog-share.js?v=${v}" defer></script>\n` +
    html.slice(bodyEnd)
  );
}

function ensureSkipTarget(html, override) {
  html = html.replace(/\s*id="sf-main" tabindex="-1"/g, '');

  const from = html.indexOf('<!-- /SF-CHROME:HEADER -->');
  const to = html.indexOf('<!-- SF-CHROME:FOOTER');
  if (from === -1 || to === -1 || to < from) return html;
  const head = html.slice(0, from), body = html.slice(from, to), tail = html.slice(to);

  const candidates = override
    ? [new RegExp(`<([a-z]+)(\\s[^>]*class="${override}"[^>]*)>`)]
    : ['main', 'article', 'section'].map((t) => new RegExp(`<(${t})(\\s[^>]*)?>`));

  for (const re of candidates) {
    const m = body.match(re);
    if (!m) continue;
    return head + body.replace(re, (full, tag, attrs = '') => {
      const cleaned = String(attrs || '').replace(/\s*id="[^"]*"/, '');
      return `<${tag} id="sf-main" tabindex="-1"${cleaned}>`;
    }) + tail;
  }
  return html;
}

let changed = 0, skipped = [];

for (const page of PAGES) {
  const path = join(ROOT, page.file);
  let html;
  try {
    html = readFileSync(path, 'utf8');
  } catch {
    skipped.push(`${page.file} (missing)`);
    continue;
  }
  const before = html;

  html = stripBrokenChromePrefix(html);

  const h = findBlock(html, 'header.sf-hdr') || findBlock(html, page.header);
  if (h) {
    const { start, end } = withMarkers(html, h, 'HEADER');
    html = html.slice(0, start) + header(page.cart) + html.slice(end);
  } else {
    skipped.push(`${page.file} header (${page.header} not found)`);
  }

  const f = findBlock(html, 'footer.sf-ftr') || findBlock(html, page.footer);
  if (f) {
    const marked = withMarkers(html, f, 'FOOTER');
    const start = cutBuy(html, marked.start);
    const insert = (page.buy ? BUY_MODULE + '\n' : '') + FOOTER;
    html = html.slice(0, start) + insert + html.slice(marked.end);
  } else {
    skipped.push(`${page.file} footer (${page.footer} not found)`);
  }

  html = ensureSkipTarget(html, page.skip);
  html = ensureAssets(html);
  html = ensureShareScript(html);
  html = ensureCheckout(html);

  if (html !== before) {
    changed++;
    if (!CHECK) writeFileSync(path, html);
    console.log(`${CHECK ? 'would update' : 'updated'}  ${relative(ROOT, path)}`);
  }
}

if (skipped.length) {
  console.log('\nskipped:');
  for (const s of skipped) console.log('  ' + s);
}
console.log(`\n${changed} page(s) ${CHECK ? 'would change' : 'changed'}.`);
