/* =====================================================================
   apply-chrome.mjs — stamp the canonical header + footer onto every page
   =====================================================================
   This repo has no build step: every page is hand-written HTML. That is
   fine until you need the SAME header on 24 of them, at which point
   hand-editing guarantees drift — which is exactly how the site ended up
   with four different headers and three different footers.

   This script is the substitute for a layout template. It:

     1. replaces whatever chrome a page currently has (`.p-nav`,
        `.blog-nav`, `.b-nav`, `nav.site-nav`, `header.site`, and the
        matching footers) with the canonical markup below;
     2. makes sure `soft.css`, `chrome.css` and `chrome.js` are linked LAST
        in <head>, each carrying a content hash in its query string.

   Re-running it is safe and idempotent: it rewrites the region between
   the chrome markers rather than appending.

       node scripts/apply-chrome.mjs           # write
       node scripts/apply-chrome.mjs --check   # report, change nothing

   Edit the HEADER / FOOTER constants here, re-run, commit the result.

   RE-RUN THIS AFTER EVERY EDIT TO soft.css / chrome.css / chrome.js — see
   the cache-busting note on hashOf() below. It is why those edits do not
   reach anyone who has already visited the site until you do.
   ===================================================================== */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');

/* --- cache busting ---------------------------------------------------
   `vercel.json` serves everything under /assets with

       Cache-Control: public, max-age=31536000, immutable

   `immutable` means the browser will not revalidate for a year. Combined
   with an unversioned URL, that froze every returning visitor on whatever
   copy of soft.css they happened to fetch first: a design change would ship,
   the deploy would go green, and the site would still look the same on any
   device that had loaded it before. Three separate rounds of fixes appeared
   not to work for exactly this reason.

   The rest of the site already handles this by hand (`blog.css?v=6`), which
   only works if someone remembers to bump it. Hashing the file contents
   makes the URL change automatically when — and only when — the file does.
   ---------------------------------------------------------------------- */
function hashOf(relPath) {
  try {
    return createHash('sha256')
      .update(readFileSync(join(ROOT, relPath)))
      .digest('hex')
      .slice(0, 8);
  } catch {
    return '0';
  }
}

/* --- the one header -------------------------------------------------
   The cart control is the single element that legitimately differs: on
   /odorstrike it opens the real drawer and its badge is driven by that
   page's own checkout JS (`#cartCount`); everywhere else it is a link
   into the product page with `?cart=open`, and chrome.js fills the badge
   from localStorage. Everything around it is identical.               */
const CART_ICON = `<svg viewBox="0 0 576 512" fill="currentColor" aria-hidden="true"><path d="M0 24C0 10.7 10.7 0 24 0L69.5 0c22 0 41.5 12.8 50.6 32l411 0c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3l-288.5 0 5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5L488 368c13.3 0 24 10.7 24 24s-10.7 24-24 24l-288.3 0c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5L24 48C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/></svg>`;

const CART = {
  link: `<a class="sf-cart" href="/odorstrike?cart=open" aria-label="Cart — view what you've added">
          ${CART_ICON}
          <span class="sf-cart__count" id="sfCartCount" hidden>0</span>
        </a>`,
  drawer: `<button class="sf-cart" type="button" id="cartBtn" onclick="openCartDrawer()" aria-label="Open cart">
          ${CART_ICON}
          <span class="sf-cart__count" id="cartCount" data-empty="1">0</span>
        </button>`,
};

/* The skip link is part of the header block so all 24 pages get it from one
   place. Before this it existed on exactly two — index.html and
   odorstrike.html — each hand-rolled with its own CSS and its own target
   (`#main`, `#buy`), which left 22 pages with no way to bypass a nav of six
   links (WCAG 2.4.1). ensureSkipTarget() below stamps the matching id. */
const SKIP = `<a class="sf-skip" href="#sf-main">Skip to content</a>`;

const header = (cart = 'link') => `<!-- SF-CHROME:HEADER — generated by scripts/apply-chrome.mjs. Edit there, not here. -->
${SKIP}
<header class="sf-hdr">
  <div class="sf-wrap">
    <div class="sf-hdr__row">
      <a href="/" class="sf-hdr__logo" aria-label="Smelloff home">
        <img src="/assets/brand/logo-smelloff-white.png?v=2" alt="SMELLOFF" width="1200" height="261" decoding="async">
      </a>
      <div class="sf-hdr__right">
        ${CART[cart]}
        <ul class="sf-nav">
          <li><a href="/odorstrike">ODORSTRIKE</a></li>
          <li><a href="/blog">Guides</a></li>
          <li><a href="/reviews">Reviews</a></li>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/track-order">Track order</a></li>
        </ul>
        <a href="/odorstrike#buy" class="sf-hdr__cta">Buy ₹229</a>
        <button class="sf-burger" type="button" aria-expanded="false" aria-controls="sfMenu" aria-label="Open menu">
          <span></span><span></span><span></span>
        </button>
      </div>
    </div>
    <ul class="sf-hdr__menu" id="sfMenu">
      <li><a href="/odorstrike">ODORSTRIKE</a></li>
      <li><a href="/blog">Guides</a></li>
      <li><a href="/reviews">Reviews</a></li>
      <li><a href="/faq">FAQ</a></li>
      <li><a href="/track-order">Track order</a></li>
      <li><a href="/contact">Contact</a></li>
    </ul>
  </div>
</header>
<!-- /SF-CHROME:HEADER -->`;

const HEADER = header();

/* --- the one footer -------------------------------------------------- */
const SOCIALS = [
  ['https://instagram.com/smelloffindia', 'Instagram', 'icon-instagram-white.png'],
  ['https://x.com/smelloffindia', 'X (Twitter)', 'icon-x.png'],
  ['https://t.me/smelloffindia', 'Telegram', 'icon-telegram-white.png'],
  ['https://www.linkedin.com/company/smelloff', 'LinkedIn', 'icon-linkedin-white.png'],
  ['https://www.facebook.com/share/1BU1dCAttY/', 'Facebook', 'icon-facebook-white.png'],
  ['https://wa.me/919392974031', 'WhatsApp', 'icon-whatsapp-white.png'],
]
  .map(
    ([href, label, icon]) =>
      `        <a href="${href}" target="_blank" rel="noopener" aria-label="${label}"><img src="/assets/${icon}" alt="" width="20" height="20" loading="lazy"></a>`
  )
  .join('\n');

const FOOTER = `<!-- SF-CHROME:FOOTER — generated by scripts/apply-chrome.mjs. Edit there, not here. -->
<footer class="sf-ftr">
  <div class="sf-wrap">
    <div class="sf-ftr__grid">
      <div class="sf-ftr__brand">
        <img src="/assets/brand/logo-smelloff-white.png?v=2" alt="SMELLOFF" width="1200" height="261" loading="lazy">
        <p>Pocket-sized fabric odor neutralizer. Made for clothes. Smell Proof. Always.</p>
      </div>
      <div>
        <h3>Shop</h3>
        <ul>
          <li><a href="/odorstrike">ODORSTRIKE</a></li>
          <li><a href="/track-order">Track order</a></li>
          <li><a href="/reviews">Reviews</a></li>
          <li><a href="/blog">Guides</a></li>
        </ul>
      </div>
      <div>
        <h3>Support</h3>
        <ul>
          <li><a href="/contact">Contact</a></li>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/shipping">Shipping</a></li>
          <li><a href="/returns">Returns</a></li>
          <li><a href="/refund">Refunds</a></li>
          <li><a href="/cancellation">Cancellation</a></li>
        </ul>
      </div>
      <div>
        <h3>Company</h3>
        <ul>
          <li><a href="/about">About</a></li>
          <li><a href="/privacy">Privacy</a></li>
          <li><a href="/terms">Terms</a></li>
          <li><a href="https://partners.smelloff.in">Partners</a></li>
        </ul>
      </div>
      <!-- The socials are a grid child in their own right, not nested inside
           the Company column. Nested, "grid-column: 1 / -1" had nothing to
           span and they wrapped two-per-row inside a narrow column. -->
      <div class="sf-ftr__socials">
${SOCIALS}
      </div>
    </div>
    <div class="sf-ftr__bottom">
      <span>© 2026 SMELLOFF. HYDERABAD. MFG: Jogdhande Nikhil Patil, Sanathnagar, Erragadda, Hyderabad.</span>
      <span>MADE IN INDIA / FABRIC ONLY</span>
    </div>
    <!-- Trademark / affiliation notice.
         The site names Febreze 166 times and Ambi Pur 51 times across two
         head-to-head comparison posts, the PDP comparison tile and the FAQ,
         and carried no disclaimer anywhere. Google Merchant Center's
         Misrepresentation policy lists "falsely implying affiliation with, or
         endorsement by, another individual, organisation, product or service"
         under prohibited misleading offers, and its best practices say: "If
         you reference another brand but you're not an official or authorised
         partner, consider a disclaimer on your website and in your ads."
         Suspension under that policy is immediate and without prior warning,
         so the cheapest possible insurance is one line on every page. -->
    <div class="sf-ftr__disclaimer">
      <span>Febreze, Ambi Pur and all other product names, logos and brands mentioned on this site are the property of their respective owners. Smelloff is not affiliated with, endorsed by or sponsored by any of them. Comparisons are our own independent assessments, published for information only.</span>
    </div>
  </div>
</footer>
<!-- /SF-CHROME:FOOTER -->`;

/* --- what to replace, per page --------------------------------------
   Each entry names the exact opening tag of the block to swap out. The
   matcher walks the tag's own nesting so it can cut a <nav> that has
   <nav>s inside it (the blog footer does).                            */
const PAGES = [
  // policy + utility pages: `.p-nav` / `.p-footer`, or a bare <footer>
  ...[
    'faq.html', 'about.html', 'contact.html', 'reviews.html', 'track-order.html',
    'privacy.html', 'terms.html', 'returns.html', 'refund.html', 'shipping.html',
    'cancellation.html', 'payment-failed.html',
  ].map((f) => ({ file: f, header: 'nav.p-nav', footer: 'footer' })),
  // 404 borrows the blog chrome
  { file: '404.html', header: 'nav.blog-nav', footer: 'footer.blog-footer' },
  // blog index has its own drawer-based nav
  { file: 'blog/index.html', header: 'nav.b-nav', footer: 'footer.blog-footer', skip: 'b-hero' },
  // the posts
  ...[
    'why-i-built-odorstrike', 'odorstrike-review-30-day-india-test',
    'odorstrike-vs-febreze-india', 'ambi-pur-vs-odorstrike',
    'what-is-fabric-odor-eliminator', 'hpbcd-cyclodextrin-fabric-odor',
    'zinc-pca-fabric-odor-ingredient-guide', 'beta-cyclodextrin-odor-removal-science',
    // buyer-intent posts recovered from the 2026-07-28 prune
    'best-fabric-odor-spray-india-2026-body-odor', 'best-deodorant-spray-for-clothes-not-skin',
    'deodorant-vs-fabric-mist', 'spray-to-remove-sweat-smell-from-clothes-instantly',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  // posts generated with no chrome of their own: the markers get inserted
  ...[
    'does-fabric-spray-stain-clothes', 'gym-clothes-smell-after-washing',
    'odorstrike-ingredients', 'wedding-festive-wear-odor-guide', 'how-to-use-odorstrike',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  // 2026-08 series: monsoon, denim, travel, fibre reference, formalwear, buyer's guide
  ...[
    'damp-clothes-musty-smell-monsoon-fix', 'how-often-to-wash-jeans-india',
    'keep-clothes-fresh-while-travelling', 'which-fabrics-hold-odor-most',
    'remove-smell-from-blazer-without-dry-cleaning', 'fabric-deodorizer-spray-india-guide-2026',
  ].map((s) => ({ file: `blog/${s}.html`, header: 'nav.blog-nav', footer: 'footer.blog-footer' })),
  // solutions hub & regional guides
  ...[
    'solutions/index.html',
    'solutions/monsoon-damp-fabric-care.html',
    'solutions/post-gym-workout-sweat-spray.html',
    'solutions/office-commute-fabric-refresher.html',
    'solutions/denim-outerwear-dry-care.html',
  ].map((f) => ({ file: f, header: 'header', footer: 'footer' })),
  // the two self-contained pages
  { file: 'index.html', header: 'header.site', footer: 'footer' },
  { file: 'odorstrike.html', header: 'nav.site-nav', footer: 'footer', cart: 'drawer', skip: 'product-hero' },
];

/* --- helpers --------------------------------------------------------- */

/** Find `<tag class="cls">…</tag>`, honouring nesting of the same tag. */
function findBlock(html, selector) {
  const [tag, cls] = selector.split('.');
  const openRe = new RegExp(`<${tag}(\\s[^>]*)?>`, 'gi');
  let m;
  while ((m = openRe.exec(html))) {
    const attrs = m[1] || '';
    if (cls) {
      const c = /class\s*=\s*"([^"]*)"/i.exec(attrs);
      if (!c || !c[1].split(/\s+/).includes(cls)) continue;
    }
    // walk forward counting same-tag opens/closes
    const walk = new RegExp(`<(/?)${tag}(\\s[^>]*)?>`, 'gi');
    walk.lastIndex = m.index;
    let depth = 0, w;
    while ((w = walk.exec(html))) {
      depth += w[1] === '/' ? -1 : 1;
      if (depth === 0) return { start: m.index, end: w.index + w[0].length };
    }
  }
  return null;
}

/** Widen the cut to swallow any previously generated marker comments. */
function withMarkers(html, block, kind) {
  let { start, end } = block;
  const open = `<!-- SF-CHROME:${kind}`;
  const close = `<!-- /SF-CHROME:${kind} -->`;
  const before = html.lastIndexOf(open, start);
  if (before !== -1 && start - before < 400) start = before;
  const after = html.indexOf(close, end);
  if (after !== -1 && after - end < 400) end = after + close.length;
  return { start, end };
}

/** Ensure the chrome assets are linked LAST in <head>.
 *
 *  "Last" is the whole point and it is easy to get wrong. soft.css and
 *  chrome.css win by source order, not specificity — most of their rules sit
 *  at the same weight as the page's own. The first version of this function
 *  parked them right after each other wherever soft.css already was, which on
 *  the blog put them *before* `blog.css`. blog.css then re-declared
 *  `.faq details { border-radius: 0 }` and its own summary padding, so blog
 *  FAQs came out square and double-padded while every other page's were
 *  round and compact.
 *
 *  So: strip any existing copies, then re-insert both immediately before
 *  </head>, after every other stylesheet the page loads.
 */
function ensureAssets(html) {
  const softTag = `<link rel="stylesheet" href="/assets/css/soft.css?v=${hashOf('assets/css/soft.css')}">`;
  const chromeTag = `<link rel="stylesheet" href="/assets/css/chrome.css?v=${hashOf('assets/css/chrome.css')}">`;
  const jsTag = `<script src="/assets/js/chrome.js?v=${hashOf('assets/js/chrome.js')}" defer></script>`;

  // Drop existing references (any attribute order / query string) and the
  // banner comment, so a re-run relocates them instead of stacking copies.
  html = html.replace(/[ \t]*<!-- Shared layers load LAST[^>]*-->\n?/g, '');
  html = html.replace(
    /[ \t]*<link[^>]+href="\/assets\/css\/(?:soft|chrome)\.css[^"]*"[^>]*>\n?/g,
    ''
  );
  html = html.replace(
    /[ \t]*<script[^>]+src="\/assets\/js\/chrome\.js[^"]*"[^>]*><\/script>\n?/g,
    ''
  );

  // These are hand-linked per page rather than inserted here, but they sit
  // under the same immutable cache rule — so re-stamp their query strings in
  // place. Without it a change is invisible to returning visitors for a year.
  //
  // tokens.css was the only one being stamped; the other three were shipping
  // unversioned under `Cache-Control: public, max-age=31536000, immutable`,
  // which is the exact trap this file's hashOf() note describes for soft.css.
  // consent-analytics.js is the expensive one: it carries the consent gate,
  // the GA4/Pixel/Clarity loaders and the injected consent bar for the 30
  // pages that don't have an inline copy, so it is the file most likely to
  // need a change to reach everyone at once — and the least likely to.
  for (const [file, pattern] of [
    ['assets/css/tokens.css', /(href="\/assets\/css\/tokens\.css)(\?[^"]*)?"/g],
    ['assets/fonts.css', /(href="\/assets\/fonts\.css)(\?[^"]*)?"/g],
    ['assets/js/consent-analytics.js', /(src="\/assets\/js\/consent-analytics\.js)(\?[^"]*)?"/g],
    // blog-share.js is NOT stamped here — see ensureShareScript(), which
    // inserts it rather than only re-stamping a tag that already exists.
    ['assets/js/track.js', /(src="\/assets\/js\/track\.js)(\?[^"]*)?"/g],
    ['assets/js/google-customer-reviews.js', /(src="\/assets\/js\/google-customer-reviews\.js)(\?[^"]*)?"/g],
  ]) {
    const v = hashOf(file);
    if (v) html = html.replace(pattern, `$1?v=${v}"`);
  }

  const headEnd = html.lastIndexOf('</head>');
  if (headEnd === -1) return html;
  return (
    html.slice(0, headEnd) +
    `<!-- Shared layers load LAST so they win on source order; ?v= is a content hash (cache busting). See scripts/apply-chrome.mjs. -->\n` +
    `${softTag}\n${chromeTag}\n${jsTag}\n` +
    html.slice(headEnd)
  );
}

/* Load the share widget's script wherever the widget itself appears.
 *
 * The buttons in `.post-share` ship with NO href — blog-share.js writes one on
 * each from the page's canonical URL. So a post that carries the widget and
 * does not load the script has seven dead controls: an <a> without an href is
 * not a link, so it takes no click, no focus and no pointer cursor; the
 * native-share button stays `hidden`; and copy-link never gets its listener.
 * Nothing looks broken — the icons render fine — which is why it survived.
 *
 * It survived because the tag was hand-linked per page and the stamping loop
 * in ensureAssets() only rewrites a tag that is ALREADY present, so it was a
 * silent no-op on any page missing one. 11 of 23 posts were in that state:
 * the five generated on 2026-07-29 and the six added on 2026-08-03, i.e.
 * every post written after the convention was set and never written down.
 *
 * Keying the insert off the widget's own presence is what stops it recurring.
 */
function ensureShareScript(html) {
  // Drop any existing reference first so a re-run relocates it rather than
  // stacking copies, the same way the header/footer/chrome.js tags are handled.
  html = html.replace(
    /[ \t]*<script[^>]+src="\/assets\/js\/blog-share\.js[^"]*"[^>]*><\/script>\n?/g,
    ''
  );
  if (!/class="post-share"/.test(html)) return html;

  const bodyEnd = html.lastIndexOf('</body>');
  if (bodyEnd === -1) return html;
  const v = hashOf('assets/js/blog-share.js');
  return (
    html.slice(0, bodyEnd) +
    `<script src="/assets/js/blog-share.js?v=${v}" defer></script>\n` +
    html.slice(bodyEnd)
  );
}

/* Give the skip link something to land on.
 *
 * Only 2 of 38 pages carried an id the link could target, and 18 of them —
 * every blog page — have no <main> at all, just an <article>. So: prefer a
 * real <main>, fall back to the first <article>, then to the first <section>
 * (the blog index, which is a stack of sections under a hero).
 *
 * tabindex="-1" is not optional. Without it the browser scrolls to the target
 * but leaves focus on the link, so the next Tab returns to the top of the nav
 * and the skip link has done nothing for the keyboard user it exists for.
 */
function ensureSkipTarget(html, override) {
  html = html.replace(/\s*id="sf-main" tabindex="-1"/g, '');   // idempotent re-stamp

  // The search is bounded to the body region between the two generated
  // blocks. Unbounded, odorstrike.html picked up the <main class="po-main">
  // that lives inside its payment-failed policy overlay — real markup, wrong
  // content, and below the footer in source order.
  const from = html.indexOf('<!-- /SF-CHROME:HEADER -->');
  const to = html.indexOf('<!-- SF-CHROME:FOOTER');
  if (from === -1 || to === -1 || to < from) return html;
  const head = html.slice(0, from), body = html.slice(from, to), tail = html.slice(to);

  // An explicit selector wins, for the pages where "first landmark" is not
  // the thing a keyboard user wants. On the PDP the first <section> in range
  // is `.showcase`, 3600px down — past the gallery, the price and the buy
  // panel, i.e. past everything the page exists for.
  const candidates = override
    ? [new RegExp(`<([a-z]+)(\\s[^>]*class="${override}"[^>]*)>`)]
    : ['main', 'article', 'section'].map((t) => new RegExp(`<(${t})(\\s[^>]*)?>`));

  for (const re of candidates) {
    const m = body.match(re);
    if (!m) continue;
    return head + body.replace(re, `<${m[1]} id="sf-main" tabindex="-1"${m[2] || ''}>`) + tail;
  }
  return html;
}

/* --- run -------------------------------------------------------------- */
let changed = 0, skipped = [];

for (const page of PAGES) {
  const path = join(ROOT, page.file);
  let html;
  try {
    html = readFileSync(path, 'utf8');
  } catch {
    skipped.push(`${page.file} (missing)`);
    continue;
  }
  const before = html;

  // On a first run the page still has its original chrome; on every run
  // after that it has ours, so both selectors have to be tried.
  const h = findBlock(html, 'header.sf-hdr') || findBlock(html, page.header);
  if (h) {
    const { start, end } = withMarkers(html, h, 'HEADER');
    html = html.slice(0, start) + header(page.cart) + html.slice(end);
  } else {
    skipped.push(`${page.file} header (${page.header} not found)`);
  }

  const f = findBlock(html, 'footer.sf-ftr') || findBlock(html, page.footer);
  if (f) {
    const { start, end } = withMarkers(html, f, 'FOOTER');
    html = html.slice(0, start) + FOOTER + html.slice(end);
  } else {
    skipped.push(`${page.file} footer (${page.footer} not found)`);
  }

  html = ensureSkipTarget(html, page.skip);
  html = ensureAssets(html);
  html = ensureShareScript(html);

  if (html !== before) {
    changed++;
    if (!CHECK) writeFileSync(path, html);
    console.log(`${CHECK ? 'would update' : 'updated'}  ${relative(ROOT, path)}`);
  }
}

if (skipped.length) {
  console.log('\nskipped:');
  for (const s of skipped) console.log('  ' + s);
}
console.log(`\n${changed} page(s) ${CHECK ? 'would change' : 'changed'}.`);
