-- Transactional email send ledger + Resend webhook delivery tracking.
-- Service-role only. RLS enabled with no anon/authenticated policies.

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  order_code text,
  email_type text not null,
  idempotency_key text not null unique,
  recipient_masked text,
  sender text,
  provider text not null default 'resend',
  provider_email_id text,
  status text not null,
  error_code text,
  error_message text,
  originating_route text,
  last_webhook_event text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists email_events_order_code_idx
  on public.email_events (order_code);

create index if not exists email_events_provider_email_id_idx
  on public.email_events (provider_email_id)
  where provider_email_id is not null;

create index if not exists email_events_status_idx
  on public.email_events (status);

create table if not exists public.email_webhook_events (
  id bigint generated by default as identity primary key,
  svix_id text not null unique,
  event_type text not null,
  provider_email_id text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists email_webhook_events_email_id_idx
  on public.email_webhook_events (provider_email_id)
  where provider_email_id is not null;

alter table public.email_events enable row level security;
alter table public.email_webhook_events enable row level security;

revoke all on table public.email_events from public, anon, authenticated;
revoke all on table public.email_webhook_events from public, anon, authenticated;

grant select, insert, update, delete on table public.email_events to service_role;
grant select, insert, update, delete on table public.email_webhook_events to service_role;

grant usage, select on sequence public.email_events_id_seq to service_role;
grant usage, select on sequence public.email_webhook_events_id_seq to service_role;
